CREATE TABLE IF NOT EXISTS USER_LOGIN
(
    USER_ID VARCHAR(15) NOT NULL          COMMENT'--用户账号',
    USER_PASSWORD VARCHAR(20) NOT NULL    COMMENT'--用户账号',
    USER_TYPE CHAR(1) NOT NULL            COMMENT'--用户类型 0：管理员，1：工作人员，2：访客',
    USER_STATUS CHAR(1) NOT NULL         COMMENT'--用户状态 0：正常，1：冻结',
    PRIMARY KEY(USER_ID)
    )COMMENT '--用户登录表';



CREATE TABLE IF NOT EXISTS USER_INFO
(
    USER_ID VARCHAR(15) NOT NULL  COMMENT'--用户账号',
    USER_NAME VARCHAR(20)       COMMENT'--用户名称',
    USER_GENDER CHAR(1) NOT NULL    COMMENT'--用户性别 0：男，1：女',
    USER_PSPT_ID CHAR(18) NOT NULL  COMMENT'--用户身份证号',
    USER_PHONE CHAR(11) NOT NULL    COMMENT'--用户手机号',
    USER_EMAIL VARCHAR(30)        COMMENT'--用户邮箱',
    PRIMARY KEY(USER_ID)
    )   COMMENT '--用户信息表';


CREATE TABLE IF NOT EXISTS AUTHOR_INFO
(
    AUTHOR_ID VARCHAR(10) NOT NULL  COMMENT'--作者编号',
    AUTHOR_NAME VARCHAR(50) NOT NULL    COMMENT'--作者名称',
    AUTHOR_STATUS CHAR(1) NOT NULL  COMMENT'--作者信息状态 0：正常，1：失效',
    PRIMARY KEY (AUTHOR_ID)
    )   COMMENT '--作者信息表';


CREATE TABLE IF NOT EXISTS PRESS_INFO
(
    PRESS_ID VARCHAR(10) NOT NULL  COMMENT'--出版社编号',
    PRESS_NAME VARCHAR(50) NOT NULL  COMMENT'--出版社名称',
    PRESS_STATUS CHAR(1) NOT NULL COMMENT'--出版社信息状态 0：正常，1：失效',
    PRIMARY KEY (PRESS_ID)
    )   COMMENT '--出版社信息表';



CREATE TABLE IF NOT EXISTS BOOK_TYPE_INFO
(
    BOOK_TYPE_ID CHAR(1) NOT NULL   COMMENT'--图书类型编号',
    BOOK_TYPE_NAME VARCHAR(50) NOT NULL COMMENT'--图书类型名称',
    BOOK_TYPE_STATUS CHAR(1) NOT NULL    COMMENT'--图书类型信息状态 0：正常，1：失效',
    PRIMARY KEY (BOOK_TYPE_ID)
    )   COMMENT '--图书类型信息表';



CREATE TABLE IF NOT EXISTS BOOK_INFO
(
    BOOK_ID VARCHAR(10) NOT NULL  COMMENT'--图书编号',
    BOOK_NAME VARCHAR(50) NOT NULL    COMMENT'--图书名称',
    BOOK_AUTHOR_ID VARCHAR(10) NOT NULL   COMMENT'--图书作者编号',
    BOOK_PRESS_ID VARCHAR(10) NOT NULL    COMMENT'--图书出版社编号',
    BOOK_TYPE_ID CHAR(1) NOT NULL    COMMENT'--图书类型编号',
    BOOK_PRICE DECIMAL(10,2) NOT NULL    COMMENT'--图书价格',
    BOOK_STATUS CHAR(1) NOT NULL    COMMENT'--图书状态 0：正常，1：借出，2：丢失',
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (BOOK_AUTHOR_ID) REFERENCES AUTHOR_INFO(AUTHOR_ID),
    FOREIGN KEY (BOOK_PRESS_ID) REFERENCES PRESS_INFO(PRESS_ID),
    FOREIGN KEY (BOOK_TYPE_ID) REFERENCES BOOK_TYPE_INFO(BOOK_TYPE_ID)
    )   COMMENT '--图书信息表';

CREATE TABLE IF NOT EXISTS BOOK_INFO(
    BOOK_ID VARCHAR(15) NOT NULL       COMMENT'--图书编号',
    BOOK_NAME VARCHAR(50) NOT NULL     COMMENT'--图书名称',
    BOOK_TYPE_ID CHAR(1) NOT NULL    COMMENT'--图书类型编号',
    AUTHOR_ID VARCHAR(10) NOT NULL     COMMENT'--作者编号',
    PRESS_ID VARCHAR(10) NOT NULL    COMMENT'--出版社编号',
    BORROWED_NUMBER INT NOT NULL    COMMENT'--借出次数',
    REMAINING_NUMBER INT NOT NULL     COMMENT'--剩余数量',
    BOOK_STATUS CHAR(1) NOT NULL        COMMENT'--图书状态 0：正常，1：借出，2：丢失',
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (BOOK_TYPE_ID) REFERENCES BOOK_TYPE_INFO (BOOK_TYPE_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR_INFO (AUTHOR_ID),
    FOREIGN KEY (PRESS_ID) REFERENCES PRESS_INFO (PRESS_ID)
    )COMMENT '--图书信息表';
CREATE TABLE IF NOT EXISTS BORROWED_INFO(
    BORROWED_ID VARCHAR(15) NOT NULL  COMMENT'--借阅编号',
    USER_ID VARCHAR(15) NOT NULL  COMMENT'--借阅用户编号',
    BOOK_ID VARCHAR(15) NOT NULL  COMMENT'--借阅图书编号',
    BORROWED_NUMBER INT NOT NULL    COMMENT'--借阅数量',
    BORROWED_START_DATE DATE NOT NULL COMMENT'--借阅开始时间',
    BORROWED_END_DATE DATE NOT NULL   COMMENT'--借阅结束时间',
    BORROW_STATUS CHAR(1) NOT NULL   COMMENT'--借阅状态 0：正常，1：逾期 2，借阅结束',
    PRIMARY KEY (BORROWED_ID)
    )   COMMENT '--借阅信息表';

